import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :module_o_mat, ModuleOMatWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# HTTPS redirect is optional and controlled at runtime via PHX_FORCE_SSL=true
# (see config/runtime.exs) when TLS terminates at a reverse proxy.
# Leave PHX_FORCE_SSL unset for direct LAN access via http://IP:PORT.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
