/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BackupDialog: typeof import('./src/components/BackupDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MaintenanceOverlay: typeof import('./src/components/MaintenanceOverlay.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    ModuleDialog: typeof import('./src/components/ModuleDialog.vue')['default']
    ModuleFilters: typeof import('./src/components/ModuleFilters.vue')['default']
    ModuleForm: typeof import('./src/components/ModuleForm.vue')['default']
    ModuleTable: typeof import('./src/components/ModuleTable.vue')['default']
    PriceHistoryDialog: typeof import('./src/components/PriceHistoryDialog.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TypeManagerDialog: typeof import('./src/components/TypeManagerDialog.vue')['default']
    YoutubeHoverPreview: typeof import('./src/components/YoutubeHoverPreview.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
